# Welcome to Jekyll!
#

# Site settings
title: Amir Hosseini
description: SAFFIRAN
owner: Amir Hosseini # or company name
first_published: 2018 # if migrating another site, the year of your first publish
email: your-email@domain.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://amir-hosseini.com" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/amirskh90
  #github: https://github.com/<username>
  #linkedin-square: https://linkedin.com/in/<username>\
  facebook-official: https://facebook.com/amirsaleh.de
  #google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  instagram: https://instagram.com/saffiran_lux
  telegram: https://telegram.me/amirskh90
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
